# Magic numbers, who doesn't love them?
MAGIC_HANDSHAKE_SERVER = 0xF8
MAGIC_HANDSHAKE_CLIENT = 0xF8
MAGIC_TRANSACT = 0x01
MAGIC_REQ_SUBSCRIBE = 0x02
MAGIC_REQ_UNSUBSCRIBE = 0x03
MAGIC_SUBSCRIBED_UPD = 0x04
MAGIC_SYSTEM_UPD = 0x05
MAGIC_EVENT_RET = 0x06
MAGIC_UPDATE_STATUS_ITEM = 0x07
MAGIC_CLEAR_STATUS_ITEM = 0x08

TRANSACT_REQ_UUID = 0x10
TRANSACT_CONN_READY = 0x11
TRANSACT_REG_SUBSYSTEM= 0x12
TRANSACT_SET_KV = 0x13
TRANSACT_GET_KV = 0x14
TRANSACT_RSET_KV = 0x15
TRANSACT_RGET_KV = 0x16
TRANSACT_GET_KV_DESC = 0x17
TRANSACT_RGET_KV_DESC = 0x18
TRANSACT_RESOLVE = 0x19
TRANSACT_GET_SUBSYSTEM = 0x20
TRANSACT_CALL_EVENT = 0x21
TRANSACT_RCALL_EVENT = 0x22
TRANSACT_GET_STATUS = 0x23

KVP_RET_AWAIT = 0
KVP_RET_HANDLE = 1

EVENT_PENDING = 0
EVENT_IN_PROGRESS = 1
EVENT_OK = 2
EVENT_REJ = 3

TRANSOP_STATE_OK = 0
TRANSOP_STATE_REJ = 1
TRANSOP_STATE_PENDING = 2

SERVER_PORT = 11750

TYPE_UNSPEC = 0
TYPE_BYTES = 1
TYPE_INT = 2