# Magic numbers, who doesn't love them?
MAGIC_HANDSHAKE_SERVER = 0xF8
MAGIC_HANDSHAKE_CLIENT = 0xF8
MAGIC_TRANSACT = 0x01
MAGIC_REQ_SUBSCRIBE = 0x02
MAGIC_REQ_UNSUBSCRIBE = 0x03
MAGIC_SUBSCRIBED_UPD = 0x04

TRANSACT_REQ_UUID = 0x10
TRANSACT_CONN_READY = 0x11
TRANSACT_REG_SUBSYSTEM= 0x12
TRANSACT_SET_KV = 0x13
TRANSACT_GET_KV = 0x14
TRANSACT_RSET_KV = 0x15
TRANSACT_RGET_KV = 0x16
TRANSACT_RGET_KV_DESC = 0x17

KVP_RET_AWAIT = 0
KVP_RET_HANDLE = 1


KV_STATE_OK = 0
KV_STATE_REJ = 1
KV_STATE_PENDING = 2

SERVER_PORT = 11750

TYPE_UNSPEC = 0
TYPE_BYTES = 1
TYPE_INT = 2